<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    /*public function authorize()
    {
        return false;
    }
    */
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => ['required', 'alpha', 'min:3', 'max:50'],
            'email'  => ['required', 'email:rfc,dns', 'max:50'],
            'password'  => ['required', 'string', 'max:200']
        ];
    }

    public function attributes()
    {
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
